### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by QmelZ** [DeltaNedas/rtfm#1]
Mindustry crashes when I click on the "Manuals" button.
[crash-report-08_09_2020_19_52_00.txt](https://github.com/DeltaNedas/rtfm/files/5048087/crash-report-08_09_2020_19_52_00.txt)

**Comment by Catchears** [comment]
I get exactly the same error.

**Comment by ILiekMelons** [comment]
ree

**Comment by DeltaNedas** [comment]
okay

**Comment by DeltaNedas** [comment]
what the fuck

**Comment by DeltaNedas** [comment]
1. what version
2. which button, in more menu or about (neither crash me)
3. that shouldnt happen ever ever ever

**Comment by DeltaNedas** [comment]
no information
