### ISSUE TITLE
Failed to build two pages

### ISSUE THREAD

**Issue by Tynach** [DeltaNedas/rtfm#10]
The following pages fail to build, with the given error displayed in the middle of the screen vertically, on the left side:

1. RTFM Docs / Manual Format
    `TypeError: Cannot find function join in object #. (builder#151(eval)#1)`

2. Modding / Units
    `InternalError: TypeError: redeclaration of var u. (builder#151(eval)#1) (builder#151(eval)#1)`

Before filing this bug report, I made sure to remove all mods from my game install and then only add the `ui-lib` and `rtfm` mods, to both make sure they were the newest version *and* to prevent any possible clashes from other mods being the problem.

I'm using Mindustry version 122, specifically the Mindustry.jar file downloaded from the release on Github.

My operating system is KDE Neon, which is based on Ubuntu 20.04. I run the game through the OpenJDK Java 11 runtime, with this being the output of `java -version`:

> ```
> Picked up _JAVA_OPTIONS: -Dswing.aatext=true
> openjdk version "11.0.9.1" 2020-11-04
> OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
> OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
> ```

**Comment by King-BR** [comment]
Same error on windows 10 with JDK 15 and on Android 9 (moto Z3 play)

**Comment by DeltaNedas** [comment]
https://github.com/mozilla/rhino/issues/790
cant fix
