### ISSUE TITLE
Stuck on instructions page

### ISSUE THREAD

**Issue by Austin5003** [DeltaNedas/rtfm#16]
After the instruction manual is opened from a processor GUI, all other buttons to open the manual open there with no way to access other pages

**Comment by Austin5003** [comment]
This also applies to the anuke logic page if opened from the processor GUI

**Comment by liuxilu** [comment]
+1

**Comment by DeltaNedas** [comment]
oh no

**Comment by DeltaNedas** [comment]
ok epic i had a thing in the api to view a page temporarily but didnt use it

**Comment by DeltaNedas** [comment]
fixed in rtfm and anuke-logic
