### ISSUE TITLE
`pathfind` isn't a default AI

### ISSUE THREAD

**Issue by Nakilon** [DeltaNedas/rtfm#19]
I feel like this is wrong:

https://github.com/DeltaNedas/rtfm/blob/ffd7586e6195ca0d2cc0c4f6cb2eaef3ea6b64ab/manuals/Logic/Instructions#L250

The `pathfind` makes Crawlers run towards the enemy spawn, just surround it and do nothing -- pretty much useless. While the uncontrolled Crawler not just runs obeying the Attack Control Center mode but also eplodes when hits any enemy structure.

**Comment by Nakilon** [comment]
Also it works weirdly for Horizon -- the unit is flying but the `findpath` leads it around the walls and the flight ends not even on the enemy base but 10 blocks to the right from it.

**Comment by DeltaNedas** [comment]
this is not mindustry's bug tracker

```java
case pathfind -> {
    ai.control = type;
}
```
as far as i can tell, `pathfind` is still supposed to revert to standard controlling
