### ISSUE TITLE
Mod not working on x64 Linux

### ISSUE THREAD

**Issue by raqu73** [DeltaNedas/rtfm#20]
On the latest 6.0 stable release, the game crashes with the following info: https://hastebin.com/jogiciluxe.apache
On BE builds, the game logs an error to the console but doesn't crash: https://hastebin.com/diguqipupo.properties
In the latter case, the mod remains enabled but does not function at all.
The mod functions fine on the same BE builds for Android.

**Comment by DeltaNedas** [comment]
works fine on debian stable amd64, mindustry v131, openjdk-jre-17-headless
