### ISSUE TITLE
Can´t see the button inside "More" tab nor on the processors

### ISSUE THREAD

**Issue by M1th0** [deltanedas/rtfm#34]
[last_log.txt](https://github.com/deltanedas/rtfm/files/9126386/last_log.txt)
The mod loads perfectly, but doesn´t show any access to the manuals 
(rhino.EcmaError: ReferenceError: "Scripts" is not defined. (library#21))

**Comment by harry0805** [comment]
I have the same issue, no manual button in about menu and the 'more' menu when I install uiLibs.

**Comment by theperspectiv** [comment]
Same issue here, build 138.1. Only mods installed are ui-lib and rtfm

**Comment by theperspectiv** [comment]
Is there another way to install the mod, other than through the in-game mod browser? Wondering if that version is out of date or broken, and maybe downloading/installing it "manually" would fix the issue.

**Comment by phbice** [comment]
I have the same issue. I'm in build 138.1, there is no "about" button in the main menu, it is folded in the "database" menu.

**Comment by deltanedas** [comment]
ui lib has been fixed
