### ISSUE TITLE
Yup

### ISSUE THREAD

**Issue by T1murik** [DeltaNedas/rtfm#7]
![изображение](https://user-images.githubusercontent.com/73241663/100908620-c0fa2300-34dc-11eb-97de-0b50a57ee150.png)
add setting to hide this button/hide automatically on pc?

**Comment by DeltaNedas** [comment]
hhh ok

**Comment by DeltaNedas** [comment]
fixed, update ui-lib
(anuke made it so player thing showed even when there are no waves, that threw off my calculations)
