### ISSUE TITLE
No apparent change in UI after install on iOS

### ISSUE THREAD

**Issue by CodeSturgeon** [DeltaNedas/rtfm#8]
After installing the mod (v2.14.6) on iOS (121.4) I can find no way of accessing the manual. There is no `About` dialog I have been able to find on the main splash screen to contain a 'Manuals' option.

`ui-lib` (v2.16.6) was also installed, but again seemed to have no impact, either on the main menus, or the in-game controls.

**Comment by DeltaNedas** [comment]
ios isnt allowed to have an exit button do you think scripts are supported
