### ISSUE TITLE
Manual button not showing when language is set to portuguese (brazil)

### ISSUE THREAD

**Issue by King-BR** [DeltaNedas/rtfm#9]
The button to access the manuals dont show up anywhere (in-game, about section or more section) when the game language is set to portuguese (brazil)

![image](https://user-images.githubusercontent.com/51011050/103143143-e0592a00-46ef-11eb-8e0a-25d6d74083a8.png)

![image](https://user-images.githubusercontent.com/51011050/103143149-e64f0b00-46ef-11eb-8c2f-fae1bab91cdd.png)

![image](https://user-images.githubusercontent.com/51011050/103143129-a0924280-46ef-11eb-8541-1da87d6fac1a.png)

![image](https://user-images.githubusercontent.com/51011050/103143127-9bcd8e80-46ef-11eb-830f-bc9cdad54b7f.png)

Proof that the mods are installed and enabled
![image](https://user-images.githubusercontent.com/51011050/103143118-6032c480-46ef-11eb-9366-aa2a3479fb28.png)

Mindustry version: steam 122

**Comment by King-BR** [comment]
When the game language is set to english it show up

![image](https://user-images.githubusercontent.com/51011050/103143214-637a8000-46f0-11eb-9201-30daf3f21cb8.png)
![image](https://user-images.githubusercontent.com/51011050/103143222-7ab96d80-46f0-11eb-901f-c0b4661de3a3.png)
![image](https://user-images.githubusercontent.com/51011050/103143225-90c72e00-46f0-11eb-9cf6-2ad5a68feffa.png)
![image](https://user-images.githubusercontent.com/51011050/103143228-96247880-46f0-11eb-890d-dd718279afec.png)

**Comment by DeltaNedas** [comment]
need last_log.txt

**Comment by King-BR** [comment]
Oh yeah, i forgot about that. Will post it asap

**Comment by King-BR** [comment]
I tried searching for a last_log.txt but i didnt found it on the data folder (or inside any other folders), even when i tried to export the crash logs it says that dont exist any log.
![image](https://user-images.githubusercontent.com/51011050/103479038-67219d00-4da9-11eb-97f2-71f1337e172b.png)


The most similar file i found was a debug.log, but i dont know if its related to the problem.
![image](https://user-images.githubusercontent.com/51011050/103479070-ae0f9280-4da9-11eb-8863-e21e6180253e.png)


I also updated mindustry to steam build 122.1 but it didnt change anything.

**Comment by DeltaNedas** [comment]
last_log.txt should be in steam/steamapps/common/Mindustry

**Comment by King-BR** [comment]
last_log.txt isnt here
![image](https://user-images.githubusercontent.com/51011050/103760840-77798800-4ff4-11eb-81fb-a3d95514c12f.png)

**Comment by DeltaNedas** [comment]
saves?

**Comment by DeltaNedas** [comment]
oh right, there is no manual *contents* translation will fix in a min

**Comment by DeltaNedas** [comment]
done

**Comment by King-BR** [comment]
Suggestion to avoid this bug: when the manual contents translation isnt found/doesnt exist the manual defaults to english
